=== jpmrs1313/DAW2020/TPCs/T2/t2.dtd
<?xml version="1.0" encoding="UTF-8"?>


<!ELEMENT project_record (name,header,workteam,abstract,deliverables)>
<!ELEMENT name (#PCDATA) >

<!ELEMENT header (keyname,title,subtitle,begin_date,end_date,supervisor)>
<!ELEMENT keyname (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT begin_date (#PCDATA)>
<!ELEMENT end_date (#PCDATA)>
<!ELEMENT supervisor (supervisor_name,supervisor_link)>
<!ELEMENT supervisor_name (#PCDATA)>
<!ELEMENT supervisor_link (#PCDATA)>

<!ELEMENT workteam (element+)>
<!ELEMENT element (id,team_name,mail) >
<!ELEMENT id (#PCDATA)>
<!ELEMENT team_name (#PCDATA)>
<!ELEMENT mail (#PCDATA)>

<!ELEMENT abstract (paragrafo+) >
<!ELEMENT paragrafo (words+) >
<!ELEMENT words (normal|bold|italic) >
<!ELEMENT normal (#PCDATA)>
<!ELEMENT bold (#PCDATA)>
<!ELEMENT italic (#PCDATA)>

<!ELEMENT deliverables (deliverable+)>
<!ELEMENT deliverable (deliverable_name,deliverable_link)>
<!ELEMENT deliverable_name (#PCDATA)>
<!ELEMENT deliverable_link (#PCDATA)>

=== jpmrs1313/DAW2020/TPCs/T2/t2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project_record SYSTEM "file:/Users/joaosoares/Downloads/t2.dtd">
<project_record>
    <name>Project Record</name>
    <header>
        <keyname>DTD e XML</keyname>
        <title>Construção de XML e DTD</title>
        <subtitle>Relatório inserido na UC de Desenvolvimento das Aplicações Web 20/21</subtitle>
        <begin_date>Outubro 2020</begin_date>
        <end_date>Outubro 2020</end_date>
        <supervisor>
            <supervisor_name>José Carlos Ramalho</supervisor_name>
            <supervisor_link>http://www4.di.uminho.pt/~jcr/</supervisor_link>
        </supervisor>
    </header>
    <workteam>
        <element>
            <id>1</id>
            <team_name>João Soares</team_name>
            <mail>jpmrs1313@gmail.com</mail>
        </element>
    </workteam>
    <abstract>
        <paragrafo>
            <normal>Com este trabalho de casa aprendi a desenvolver um dicheiro </normal>
            <bold>DTD </bold> 
            <normal>que me permitiu validar a estrutura de um ficheiro </normal>
            <italic> XML </italic>
        </paragrafo>
    </abstract>
    <deliverables>
        <deliverable>
            <deliverable_name>t2.dt2 e t2.xml</deliverable_name>
            <deliverable_link>https://github.com/jpmrs1313/DAW2020</deliverable_link>
        </deliverable>
    </deliverables>
</project_record>

=== jpmrs1313/DAW2020/TPCs/T3/T3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project_record SYSTEM "file:/Users/joaosoares/Downloads/t2.dtd">
<project_record>
    <name>Project Record</name>
    <header>
        <keyname>XSLT</keyname>
        <title>Trabalho de Casa 3</title>
        <subtitle>Relatório do TPC</subtitle>
        <begin_date>Outubro 2020</begin_date>
        <end_date>Outubro 2020</end_date>
        <supervisor>
            <supervisor_name>José Carlos Ramalho</supervisor_name>
            <supervisor_link>http://www4.di.uminho.pt/~jcr/</supervisor_link>
        </supervisor>
    </header>
    <workteam>
        <element>
            <id>1</id>
            <team_name>João Soares</team_name>
            <mail>jpmrs1313@gmail.com</mail>
        </element>
    </workteam>
    <abstract>
        <paragrafo>
            <normal>Neste trabalho desenvolvi um ficheiro DTD que me permitiu definir a estrutura do ficheiro </normal>
            <bold>XML </bold> 
            <normal>de seguida foi necessário tornar a informação contida no ficheiro </normal>
            <italic>XML </italic>
            <normal>interpretavel ao utilizador comum, para isso foi desenvolvido um ficheiro XSL que permitiu aplicar transformacoes ao ficheiro XML de modo a criar um indice que permite aceder a informaçao detalhada do ficheiro XML </normal>
        </paragrafo>
    </abstract>
    <deliverables>
        <deliverable>
            <deliverable_name>T3.dtd</deliverable_name>
            <deliverable_link>https://github.com/jpmrs1313/DAW2020</deliverable_link>
        </deliverable>
        <deliverable>
            <deliverable_name>T3.xsl</deliverable_name>
            <deliverable_link>https://github.com/jpmrs1313/DAW2020</deliverable_link>
        </deliverable>
    </deliverables>
</project_record>
